# docker-compose up --build
# version: '2.4'

services:
  zip:
    init: true
    build:
      context: .
      target: dev
    ports: 
      - 8080:8080
      - 9229:9229
    depends_on:
      mongo:
        condition: service_healthy
    volumes: 
      - .:/app/zip:delegated
      - /app/zip/node_modules
    environment: 
      - MONGODB_URI=mongodb://mongo:27017/zip

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes: 
      - mongo-db:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet

volumes: 
  mongo-db:
