# docker-compose -f docker-compose.test.yml up --build --exit-code-from test-zip
version: '2.4'

services:
  test-zip:
    init: true
    build:
      context: .
      target: test
    ports: 
      - 8080:8080
    depends_on:
      test-mongo:
        condition: service_healthy
    volumes: 
      - .:/app/zip:delegated
      - /app/zip/node_modules
    environment: 
      - MONGODB_URI=mongodb://test-mongo:27017/test-zip
    command: ["npm", "test"]

  test-mongo:
    image: mongo:server
    ports:
      - 27017:27017
    volumes: 
      - test-mongo-db:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet

volumes: 
  test-mongo-db:
